# Generated by Django 5.2 on 2025-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sharif_line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='thank_you_message',
            field=models.TextField(default='با تشکر از مشارکت شما در این نظرسنجی', verbose_name='پیام تشکر'),
        ),
    ]
