# Generated by Django 5.2 on 2025-07-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_sharif_line', '0003_alter_question_options_question_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
    ]
