# Generated by Django 5.2 on 2025-07-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_sharif_line', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
    ]
